# This workflow will review a GloBI indexed dataset.
# For more information see: https://globalbioticinteractions.org

name: GloBI review by Elton

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: download review script
        run: curl --silent -L "https://raw.githubusercontent.com/globalbioticinteractions/globinizer/master/check-dataset.sh" > check-dataset.sh
      - name: review dataset
        run: bash check-dataset.sh "${GITHUB_REPOSITORY}"
